# Generated by Django 5.1.4 on 2026-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('platform_type', models.CharField(choices=[('uz', "O'zbekiston"), ('intl', 'Xalqaro')], default='uz', max_length=10)),
                ('base_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='ON/OFF')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority')),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('total_vacancies', models.PositiveIntegerField(default=0)),
                ('last_fetch_count', models.PositiveIntegerField(default=0)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('is_working', models.BooleanField(default=True, verbose_name='Ishlamoqda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platforma',
                'verbose_name_plural': 'Platformalar',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
