# Generated by Django 5.1.4 on 2026-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('company_type', models.CharField(blank=True, help_text='IT Company, Education Center, Fintech, etc.', max_length=100, null=True)),
                ('checked_by_ai', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('is_top', models.BooleanField(default=False, verbose_name='TOP kompaniya')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
                'ordering': ['name'],
            },
        ),
    ]
