# Generated by Django 5.1.4 on 2026-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Faoliyat tavsifi'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_real',
            field=models.BooleanField(default=True, verbose_name='Haqiqiy kompaniya'),
        ),
    ]
