# Generated by Django 5.1.4 on 2026-06-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ON/OFF')),
                ('daily_limit', models.PositiveIntegerField(default=10)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(db_index=True, max_length=300)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.category')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('found', 'Topildi'), ('new', 'Yangi'), ('duplicate', 'Duplikat'), ('sent', 'Yuborilgan'), ('skipped', "O'tkazib yuborildi")], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_logs', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Parser log',
                'verbose_name_plural': 'Parser loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated alternative names for matching')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='vacancies.category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skilllar',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['title', 'company_name'], name='vacancies_v_title_7d7b53_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-created_at'], name='vacancies_v_created_4d3c6c_idx'),
        ),
    ]
